travis:
  secure:
    BINSTAR_TOKEN: tI0U8y4WrVHIO2GfmDgk8WJlbFibXygsS5Fj3M0hIIfGcjzZGualBeaL0G6Lz55SwMQPSdizbgrCdjqycEYEy6umxZEhMFmylEAsHLnUrJETg8w7iENKUpQbEgzCNeBYwk+r9j0xq5iV1Me/ig9Sc5pZX+LDWLWR38JeVBMlKjMvwOwDYm57A7e5QVldr3TdnPG+B7SIV0PXJSB+aci1blWtVmwVwQ1xqPbFzlnNwpu/j5sWnFONM+CY27RJGreJ2U3h6hUBwC1swr9A0ZjinLAh52sLOKPxT0CWXbrZKqzTPAJyzM4VNkJAN2sT0vmcBvMnfjAACqmeMLZv0pB/XYTU77ZlKbHpba3AyFhaSrp2yoiAhj67vd89Gggz9hxZgrNqooEo+i48n38orOlzx7ux+rk/7SBbIZ3bnokboYbdISr99R8lZ0kZcgBX2e/fy5XNbfxZcq+BpxzcWZMUrjH0dQhqhy/u/TBvZ4v4qQkt+RTPnundMPzHHZIN9aE9u/RFQfnYjXQcUFb8+qeB0B4Fmo07YATNTSuyu41zh4p8ecaS85l/XNidlwmRvRjCZdrdcLz2bNxLZMf+6CX4MiHn+wArSkgXG6cgKxkyoEXInruop1WU/J+dlxnIdJWXVDbtRIXkmuBcdTWMDnTWSgkTNsJfVcraf56hc4CnRv8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
